### ISSUE TITLE
Need help regarding implementation of tradingview in IOS

### ISSUE THREAD

**Issue by reactivespace** [skela/tradingview-mobile#1]
I am trying to show my own datafeed but didn't get any solution if you have iOS implementation it will be very helpful for us Thanks

**Comment by skela** [comment]
I don't work with the customer that was using this anymore, but in any case, the iOS code that made use of it was UIWebView stuff written in Xamarin.iOS, so I doubt it would be much use to you. UIWebViews are getting deprecated in December for updates to iOS apps. Its already deprecated for new apps to the App Store. (If you try and submit a new app to the app store containing any reference or use of UIWebViews you'll get a rejection).

**Comment by reactivespace** [comment]
Would you please share some example code how did you implement that it will be helpful

**Comment by skela** [comment]
I haven't got that code anymore, as I said before I don't work for that customer anymore. Sorry :(
